=begin
#Fraud_detection

#Challenge project

The version of the OpenAPI document: v2

Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

module OpenapiClient
  VERSION = '1.0.0'
end
