=begin
#Fraud_detection

#Challenge project

The version of the OpenAPI document: v2

Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::ClassificationsShowRequest
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::ClassificationsShowRequest do
  let(:instance) { OpenapiClient::ClassificationsShowRequest.new }

  describe 'test an instance of ClassificationsShowRequest' do
    it 'should create an instance of ClassificationsShowRequest' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenapiClient::ClassificationsShowRequest)
    end
  end

  describe 'test attribute "data"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
