=begin
#Fraud_detection

#Challenge project

The version of the OpenAPI document: v2

Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::ClassificationsCreateNewRequest
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::ClassificationsCreateNewRequest do
  let(:instance) { OpenapiClient::ClassificationsCreateNewRequest.new }

  describe 'test an instance of ClassificationsCreateNewRequest' do
    it 'should create an instance of ClassificationsCreateNewRequest' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenapiClient::ClassificationsCreateNewRequest)
    end
  end

  describe 'test attribute "data"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "is_good"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
